In [113]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [114]:
df = pd.read_csv('Dataset 1.csv')

In [115]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [117]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [118]:
df.shape

(1200, 14)

In [119]:
df = df.drop(['OrderID', 'CustomerID', 'TrackingNumber', 'ShippingAddress'], axis = 1)

In [120]:
print(df.columns)

Index(['Date', 'Product', 'Quantity', 'UnitPrice', 'PaymentMethod',
       'OrderStatus', 'ItemsInCart', 'CouponCode', 'ReferralSource',
       'TotalPrice'],
      dtype='object')

In [121]:
df['CouponCode'] = df['CouponCode'].fillna('NoCoupon')
df

,Date,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,2023-01-04,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10
1,2024-08-23,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70
2,2024-02-27,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40
3,2023-10-15,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19
4,2025-05-08,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...
1195,2024-06-20,Desk,1,107.04,Credit Card,Cancelled,6,FREESHIP,Google,107.04
1196,2024-03-04,Monitor,2,662.53,Online,Cancelled,5,NoCoupon,Facebook,1325.06
1197,2023-07-13,Tablet,2,436.84,Online,Delivered,2,FREESHIP,Instagram,873.68
1198,2024-08-22,Chair,4,262.52,Debit Card,Cancelled,4,WINTER15,Instagram,1050.08
1199,2023-06-11,Tablet,4,560.58,Gift Card,Returned,6,SAVE10,Referral,2242.32

In [122]:
df['Date'] = pd.to_datetime(df['Date'])

In [123]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [124]:
df

,Date,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Day
0,2023-01-04,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10,2023,1,4
1,2024-08-23,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70,2024,8,23
2,2024-02-27,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40,2024,2,27
3,2023-10-15,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19,2023,10,15
4,2025-05-08,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04,2025,5,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-06-20,Desk,1,107.04,Credit Card,Cancelled,6,FREESHIP,Google,107.04,2024,6,20
1196,2024-03-04,Monitor,2,662.53,Online,Cancelled,5,NoCoupon,Facebook,1325.06,2024,3,4
1197,2023-07-13,Tablet,2,436.84,Online,Delivered,2,FREESHIP,Instagram,873.68,2023,7,13
1198,2024-08-22,Chair,4,262.52,Debit Card,Cancelled,4,WINTER15,Instagram,1050.08,2024,8,22
1199,2023-06-11,Tablet,4,560.58,Gift Card,Returned,6,SAVE10,Referral,2242.32,2023,6,11

In [125]:
df.drop('Date', axis = 1, inplace = True)

In [126]:
df.head()

,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Day
0,Monitor,5,570.62,Debit Card,Shipped,7,SAVE10,Instagram,2853.10,2023,1,4
1,Phone,2,151.35,Online,Shipped,3,SAVE10,Referral,302.70,2024,8,23
2,Tablet,5,550.68,Credit Card,Cancelled,8,FREESHIP,Email,2753.40,2024,2,27
3,Chair,1,273.19,Debit Card,Returned,5,SAVE10,Facebook,273.19,2023,10,15
4,Printer,4,626.01,Online,Delivered,8,SAVE10,Email,2504.04,2025,5,8

In [127]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [128]:
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [129]:
df = df.astype(int)

In [130]:
df.head()

,Product,Quantity,UnitPrice,PaymentMethod,OrderStatus,ItemsInCart,CouponCode,ReferralSource,TotalPrice,Year,Month,Day
0,3,5,570,2,4,7,2,3,2853,2023,1,4
1,4,2,151,4,4,3,2,4,302,2024,8,23
2,6,5,550,1,0,8,0,0,2753,2024,2,27
3,0,1,273,2,3,5,2,1,273,2023,10,15
4,5,4,626,4,1,8,2,0,2504,2025,5,8

In [131]:
X = df.drop('TotalPrice', axis = 1)
y = df['TotalPrice']

In [132]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Random Forest

In [169]:
from sklearn.ensemble import RandomForestRegressor

In [177]:
rf_model = RandomForestRegressor(random_state=42)

In [178]:
rf_model.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [181]:
y_pred_rf = rf_model.predict(X_test)

In [182]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R²  :", r2_score(y_test, y_pred))

MAE : 9.02220833333334
RMSE: 15.388001102049182
R²  : 0.9996887832490289

# KNN

In [165]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

KNeighborsRegressor()

In [168]:
y_pred_knn = knn.predict(X_test)
y_pred_knn

array([2264.4, 1779.6, 1779.6, 2151.2, 1779.6, 1779.6, 2144.4, 2151.2,
       2254.6, 2151.2, 1779.6, 1779.6, 2101.8, 1779.6, 1879.8, 1517.6,
       1779.6, 1517.6, 1779.6, 1779.6, 1779.6, 1779.6, 1779.6, 1781.8,
       1779.6, 2528.6, 2805.2, 1779.6, 1779.6, 1779.6, 1779.6, 1779.6,
       2154. , 2511. , 2154. , 1779.6, 2151.2, 1779.6, 2151.2, 1779.6,
       1779.6, 1779.6, 1779.6, 1517.6, 1779.6, 1779.6, 1517.6, 1779.6,
       1779.6, 2154.2, 1517.6, 1987.6, 1779.6, 1779.6, 1779.6, 2154.2,
       1781.8, 1779.6, 1779.6, 1779.6, 1517.6, 1779.6, 1779.6, 1779.6,
       1517.6, 1779.6, 1889.8, 1517.6, 1779.6, 1779.6, 1779.6, 2264.4,
       1779.6, 2151.2, 1779.6, 1517.6, 1779.6, 1779.6, 1779.6, 1779.6,
       1779.6, 2144.4, 1517.6, 2151.2, 1781.8, 1779.6, 1779.6, 1779.6,
       1779.6, 1779.6, 2528.6, 1517.6, 2151.2, 1779.6, 2366. , 1779.6,
       1517.6, 2154. , 2528.6, 1779.6, 1779.6, 1779.6, 1888. , 1517.6,
       1517.6, 1779.6, 1889.8, 1517.6, 2151.2, 2511. , 1779.6, 1779.6,
       1779.6, 2528.6, 1779.6, 1517.6, 1779.6, 1779.6, 2264.4, 1779.6,
       1517.6, 1779.6, 1779.6, 1779.6, 2264.4, 2151.2, 1779.6, 2045.4,
       1517.6, 2528.6, 1779.6, 1517.6, 1517.6, 2154. , 1779.6, 2038. ,
       1779.6, 2264.4, 1779.6, 1779.6, 1779.6, 1517.6, 1517.6, 1517.6,
       1779.6, 2258. , 2151.2, 2151.2, 2151.2, 1779.6, 1779.6, 2299.4,
       2151.2, 2528.6, 1779.6, 1779.6, 1779.6, 1779.6, 1517.6, 2264.4,
       1779.6, 2366. , 1779.6, 1517.6, 2154.2, 2154. , 1779.6, 2151.2,
       1779.6, 1779.6, 2264.4, 1889.8, 1517.6, 1779.6, 1779.6, 1779.6,
       1779.6, 1517.6, 2154.2, 2154. , 2151.2, 1517.6, 1517.6, 2154. ,
       1779.6, 1779.6, 2528.6, 2479.2, 1779.6, 2209.2, 1889.8, 1779.6,
       1779.6, 1779.6, 2154. , 1779.6, 1517.6, 1889.2, 1779.6, 2299.4,
       2151.2, 1779.6, 2257.6, 1779.6, 1517.6, 1779.6, 1517.6, 1517.6,
       1779.6, 1779.6, 1517.6, 1779.6, 1779.6, 1779.6, 2154.2, 1779.6,
       2254.6, 2151.2, 1779.6, 1779.6, 1779.6, 1517.6, 1779.6, 1987.6,
       1517.6, 1517.6, 1779.6, 1779.6, 2484.4, 2528.6, 2151.2, 2151.2,
       1517.6, 1779.6, 1779.6, 2151.2, 2528.6, 2269.4, 1517.6, 1779.6])

In [173]:
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R²  :", r2_score(y_test, y_pred))

MAE : 9.02220833333334
RMSE: 15.388001102049182
R²  : 0.9996887832490289

# Grid Search CV

In [174]:
from sklearn.model_selection import GridSearchCV

## Random Forest Regressor

In [183]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

grid = GridSearchCV(
    estimator=rf_model,
    param_grid=param_grid,
    cv=5,
    scoring='r2',          # or 'neg_mean_squared_error'
    n_jobs=-1,
    return_train_score=True
)

grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [10, 20, None],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             return_train_score=True, scoring='r2')

In [186]:
grid.cv_results_

{'mean_fit_time': array([1.28292847, 3.4827981 , 1.39939981, 2.94500246, 1.42870884,
        2.84556422, 1.36007385, 2.69726982, 1.78772573, 3.60626731,
        1.4060451 , 2.82962632, 1.42928381, 2.84039006, 1.3588726 ,
        2.73056579, 1.80953331, 3.62800026, 1.41679859, 2.85056181,
        1.44687777, 2.82086778, 1.36295538, 1.64067707]),
 'std_fit_time': array([0.3417715 , 0.301369  , 0.32337463, 0.03598148, 0.0137124 ,
        0.01019576, 0.00813352, 0.01109207, 0.00621008, 0.03061072,
        0.00737393, 0.00598038, 0.00556507, 0.00534432, 0.0039521 ,
        0.00933029, 0.00591595, 0.01590114, 0.00554792, 0.01969682,
        0.00844846, 0.04362417, 0.00803369, 0.01755879]),
 'mean_score_time': array([0.04930625, 0.08909779, 0.04654727, 0.07899942, 0.04500732,
        0.08254685, 0.04351649, 0.08069048, 0.05007577, 0.09156742,
        0.04841862, 0.08024278, 0.04587393, 0.08573804, 0.04403429,
        0.07933245, 0.0507844 , 0.09159169, 0.04567556, 0.08192773,
        0.04740677, 0.0469069 , 0.03388929, 0.02865543]),
 'std_score_time': array([0.00139673, 0.00323464, 0.00357527, 0.00234969, 0.00152725,
        0.0027007 , 0.0008042 , 0.00106819, 0.00024415, 0.00207286,
        0.00181357, 0.00168635, 0.0013211 , 0.00201006, 0.00080032,
        0.00494168, 0.00093302, 0.00299303, 0.00135688, 0.00118829,
        0.00256354, 0.00901208, 0.00410689, 0.00023225]),
 'param_max_depth': masked_array(data=[10, 10, 10, 10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 20,
                    20, 20, None, None, None, None, None, None, None, None],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_min_samples_leaf': masked_array(data=[1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1,
                    1, 1, 2, 2, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_min_samples_split': masked_array(data=[2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2, 5, 5, 2, 2,
                    5, 5, 2, 2, 5, 5],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_n_estimators': masked_array(data=[100, 200, 100, 200, 100, 200, 100, 200, 100, 200, 100,
                    200, 100, 200, 100, 200, 100, 200, 100, 200, 100, 200,
                    100, 200],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'max_depth': 10,
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'max_depth': 10,
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'max_depth': 10,
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'max_depth': 10,
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'max_depth': 10,
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'max_depth': 10,
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'max_depth': 10,
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'max_depth': 10,
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'max_depth': 20,
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'max_depth': 20,
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'max_depth': 20,
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'max_depth': 20,
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'max_depth': 20,
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'max_depth': 20,
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'max_depth': 20,
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'max_depth': 20,
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'max_depth': None,
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'max_depth': None,
   'min_samples_leaf': 1,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'max_depth': None,
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'max_depth': None,
   'min_samples_leaf': 1,
   'min_samples_split': 5,
   'n_estimators': 200},
  {'max_depth': None,
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 100},
  {'max_depth': None,
   'min_samples_leaf': 2,
   'min_samples_split': 2,
   'n_estimators': 200},
  {'max_depth': None,
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 100},
  {'max_depth': None,
   'min_samples_leaf': 2,
   'min_samples_split': 5,
   'n_estimators': 200}],
 'split0_test_score': array([0.99972903, 0.99974806, 0.99968864, 0.99972161, 0.99975503,
        0.99976846, 0.99973123, 0.99974313, 0.99973097, 0.99975193,
        0.99970264, 0.99972694, 0.99974248, 0.9997588 , 0.99973115,
        0.9997443 , 0.99973097, 0.99975193, 0.99970264, 0.99972694,
        0.99974248, 0.9997588 , 0.99973115, 0.9997443 ]),
 'split1_test_score': array([0.99965516, 0.99964231, 0.99961413, 0.99960518, 0.99963221,
        0.9996311 , 0.99963488, 0.99962559, 0.99966797, 0.99965738,
        0.99961708, 0.99961298, 0.99963688, 0.9996327 , 0.99963402,
        0.99962708, 0.99966797, 0.99965738, 0.99961708, 0.99961298,
        0.99963688, 0.9996327 , 0.99963402, 0.99962708]),
 'split2_test_score': array([0.99967342, 0.99969779, 0.99966938, 0.99967964, 0.999689  ,
        0.99970316, 0.99968607, 0.99969654, 0.99967211, 0.99971381,
        0.99965689, 0.99966977, 0.9996873 , 0.99970163, 0.99967945,
        0.99969067, 0.99967211, 0.99971381, 0.99965689, 0.99966977,
        0.9996873 , 0.99970163, 0.99967945, 0.99969067]),
 'split3_test_score': array([0.99954808, 0.99956076, 0.99950216, 0.99950159, 0.99954267,
        0.99954992, 0.99951342, 0.99951454, 0.9995413 , 0.99955369,
        0.99950512, 0.99950985, 0.99956139, 0.99957045, 0.99951572,
        0.99951543, 0.9995413 , 0.99955369, 0.99950512, 0.99950985,
        0.99956139, 0.99957045, 0.99951572, 0.99951543]),
 'split4_test_score': array([0.99984002, 0.99984396, 0.99981125, 0.99981521, 0.99982747,
        0.99983372, 0.99981105, 0.99981482, 0.99984089, 0.99984251,
        0.99980796, 0.99981615, 0.99982059, 0.99983176, 0.99980966,
        0.99981629, 0.99984089, 0.99984251, 0.99980796, 0.99981615,
        0.99982059, 0.99983176, 0.99980966, 0.99981629]),
 'mean_test_score': array([0.99968914, 0.99969858, 0.99965711, 0.99966465, 0.99968927,
        0.99969727, 0.99967533, 0.99967892, 0.99969065, 0.99970387,
        0.99965794, 0.99966714, 0.99968973, 0.99969907, 0.999674  ,
        0.99967875, 0.99969065, 0.99970387, 0.99965794, 0.99966714,
        0.99968973, 0.99969907, 0.999674  , 0.99967875]),
 'std_test_score': array([9.55578974e-05, 9.56485142e-05, 1.00757340e-04, 1.06079853e-04,
        9.81549350e-05, 9.98110659e-05, 9.95079552e-05, 1.02727624e-04,
        9.73235952e-05, 9.62757417e-05, 9.95285053e-05, 1.03403309e-04,
        8.85176131e-05, 9.17916687e-05, 9.83391634e-05, 1.02664018e-04,
        9.73235952e-05, 9.62757417e-05, 9.95285053e-05, 1.03403309e-04,
        8.85176131e-05, 9.17916687e-05, 9.83391634e-05, 1.02664018e-04]),
 'rank_test_score': array([12,  5, 24, 21, 11,  6, 16, 13,  7,  1, 22, 19,  9,  3, 17, 14,  7,
         1, 22, 19,  9,  3, 17, 14], dtype=int32),
 'split0_train_score': array([0.99995062, 0.99995333, 0.99990693, 0.99991317, 0.99993253,
        0.99993493, 0.99991247, 0.99991621, 0.99995391, 0.99995629,
        0.99990818, 0.99991506, 0.99993065, 0.99993385, 0.99991211,
        0.99991657, 0.99995391, 0.99995629, 0.99990818, 0.99991506,
        0.99993065, 0.99993385, 0.99991211, 0.99991657]),
 'split1_train_score': array([0.99994875, 0.99995346, 0.99989933, 0.99990508, 0.99992045,
        0.99992586, 0.99990295, 0.99990707, 0.99995245, 0.99995613,
        0.99990033, 0.99990535, 0.9999217 , 0.99992569, 0.99990374,
        0.9999074 , 0.99995245, 0.99995613, 0.99990033, 0.99990535,
        0.9999217 , 0.99992569, 0.99990374, 0.9999074 ]),
 'split2_train_score': array([0.99994655, 0.99995251, 0.99990205, 0.99990873, 0.9999212 ,
        0.9999283 , 0.99990204, 0.99990801, 0.99995186, 0.99995463,
        0.99990135, 0.99990741, 0.99992197, 0.99992786, 0.99990164,
        0.99990838, 0.99995186, 0.99995463, 0.99990135, 0.99990741,
        0.99992197, 0.99992786, 0.99990164, 0.99990838]),
 'split3_train_score': array([0.9999435 , 0.99995019, 0.99990356, 0.99991102, 0.99992058,
        0.99992976, 0.99990415, 0.99991105, 0.99994653, 0.99995293,
        0.99990332, 0.9999115 , 0.99992095, 0.9999293 , 0.99990304,
        0.99991054, 0.99994653, 0.99995293, 0.99990332, 0.9999115 ,
        0.99992095, 0.9999293 , 0.99990304, 0.99991054]),
 'split4_train_score': array([0.99995461, 0.99995627, 0.99991532, 0.9999181 , 0.99993268,
        0.99993547, 0.99991748, 0.99991941, 0.99995987, 0.99996245,
        0.99991603, 0.99991857, 0.99993368, 0.99993666, 0.99991618,
        0.99991905, 0.99995987, 0.99996245, 0.99991603, 0.99991857,
        0.99993368, 0.99993666, 0.99991618, 0.99991905]),
 'mean_train_score': array([0.99994881, 0.99995315, 0.99990544, 0.99991122, 0.99992549,
        0.99993087, 0.99990782, 0.99991235, 0.99995292, 0.99995649,
        0.99990584, 0.99991158, 0.99992579, 0.99993067, 0.99990734,
        0.99991239, 0.99995292, 0.99995649, 0.99990584, 0.99991158,
        0.99992579, 0.99993067, 0.99990734, 0.99991239]),
 'std_train_score': array([3.74850741e-06, 1.95029572e-06, 5.51750348e-06, 4.36029696e-06,
        5.81767982e-06, 3.75758497e-06, 6.09127934e-06, 4.75762620e-06,
        4.27657225e-06, 3.22176194e-06, 5.76614566e-06, 4.84062462e-06,
        5.30138060e-06, 4.01299464e-06, 5.74267059e-06, 4.60959052e-06,
        4.27657225e-06, 3.22176194e-06, 5.76614566e-06, 4.84062462e-06,
        5.30138060e-06, 4.01299464e-06, 5.74267059e-06, 4.60959052e-06])}

In [187]:
result1 = pd.DataFrame(grid.cv_results_)

In [188]:
result1

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,...,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,split3_train_score,split4_train_score,mean_train_score,std_train_score
0,1.282928,0.341771,0.049306,0.001397,10,1,2,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.999729,...,0.999689,0.000096,12,0.999951,0.999949,0.999947,0.999943,0.999955,0.999949,0.000004
1,3.482798,0.301369,0.089098,0.003235,10,1,2,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.999748,...,0.999699,0.000096,5,0.999953,0.999953,0.999953,0.999950,0.999956,0.999953,0.000002
2,1.399400,0.323375,0.046547,0.003575,10,1,5,100,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.999689,...,0.999657,0.000101,24,0.999907,0.999899,0.999902,0.999904,0.999915,0.999905,0.000006
3,2.945002,0.035981,0.078999,0.002350,10,1,5,200,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",0.999722,...,0.999665,0.000106,21,0.999913,0.999905,0.999909,0.999911,0.999918,0.999911,0.000004
4,1.428709,0.013712,0.045007,0.001527,10,2,2,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.999755,...,0.999689,0.000098,11,0.999933,0.999920,0.999921,0.999921,0.999933,0.999925,0.000006
5,2.845564,0.010196,0.082547,0.002701,10,2,2,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.999768,...,0.999697,0.000100,6,0.999935,0.999926,0.999928,0.999930,0.999935,0.999931,0.000004
6,1.360074,0.008134,0.043516,0.000804,10,2,5,100,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.999731,...,0.999675,0.000100,16,0.999912,0.999903,0.999902,0.999904,0.999917,0.999908,0.000006
7,2.697270,0.011092,0.080690,0.001068,10,2,5,200,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",0.999743,...,0.999679,0.000103,13,0.999916,0.999907,0.999908,0.999911,0.999919,0.999912,0.000005
8,1.787726,0.006210,0.050076,0.000244,20,1,2,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",0.999731,...,0.999691,0.000097,7,0.999954,0.999952,0.999952,0.999947,0.999960,0.999953,0.000004
9,3.606267,0.030611,0.091567,0.002073,20,1,2,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",0.999752,...,0.999704,0.000096,1,0.999956,0.999956,0.999955,0.999953,0.999962,0.999956,0.000003
10,1.406045,0.007374,0.048419,0.001814,20,1,5,100,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",0.999703,...,0.999658,0.000100,22,0.999908,0.999900,0.999901,0.999903,0.999916,0.999906,0.000006
11,2.829626,0.005980,0.080243,0.001686,20,1,5,200,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",0.999727,...,0.999667,0.000103,19,0.999915,0.999905,0.999907,0.999911,0.999919,0.999912,0.000005
12,1.429284,0.005565,0.045874,0.001321,20,2,2,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",0.999742,...,0.999690,0.000089,9,0.999931,0.999922,0.999922,0.999921,0.999934,0.999926,0.000005
13,2.840390,0.005344,0.085738,0.002010,20,2,2,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",0.999759,...,0.999699,0.000092,3,0.999934,0.999926,0.999928,0.999929,0.999937,0.999931,0.000004
14,1.358873,0.003952,0.044034,0.000800,20,2,5,100,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",0.999731,...,0.999674,0.000098,17,0.999912,0.999904,0.999902,0.999903,0.999916,0.999907,0.000006
15,2.730566,0.009330,0.079332,0.004942,20,2,5,200,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",0.999744,...,0.999679,0.000103,14,0.999917,0.999907,0.999908,0.999911,0.999919,0.999912,0.000005
16,1.809533,0.005916,0.050784,0.000933,None,1,2,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.999731,...,0.999691,0.000097,7,0.999954,0.999952,0.999952,0.999947,0.999960,0.999953,0.000004
17,3.628000,0.015901,0.091592,0.002993,None,1,2,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.999752,...,0.999704,0.000096,1,0.999956,0.999956,0.999955,0.999953,0.999962,0.999956,0.000003
18,1.416799,0.005548,0.045676,0.001357,None,1,5,100,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.999703,...,0.999658,0.000100,22,0.999908,0.999900,0.999901,0.999903,0.999916,0.999906,0.000006
19,2.850562,0.019697,0.081928,0.001188,None,1,5,200,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",0.999727,...,0.999667,0.000103,19,0.999915,0.999905,0.999907,0.999911,0.999919,0.999912,0.000005
20,1.446878,0.008448,0.047407,0.002564,None,2,2,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.999742,...,0.999690,0.000089,9,0.999931,0.999922,0.999922,0.999921,0.999934,0.999926,0.000005
21,2.820868,0.043624,0.046907,0.009012,None,2,2,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.999759,...,0.999699,0.000092,3,0.999934,0.999926,0.999928,0.999929,0.999937,0.999931,0.000004
22,1.362955,0.008034,0.033889,0.004107,None,2,5,100,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.999731,...,0.999674,0.000098,17,0.999912,0.999904,0.999902,0.999903,0.999916,0.999907,0.000006
23,1.640677,0.017559,0.028655,0.000232,None,2,5,200,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",0.999744,...,0.999679,0.000103,14,0.999917,0.999907,0.999908,0.999911,0.999919,0.999912,0.000005

In [193]:
result1[['params','param_max_depth','mean_test_score']]

,params,param_max_depth,mean_test_score
0,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",10,0.999689
1,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",10,0.999699
2,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",10,0.999657
3,"{'max_depth': 10, 'min_samples_leaf': 1, 'min_...",10,0.999665
4,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",10,0.999689
5,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",10,0.999697
6,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",10,0.999675
7,"{'max_depth': 10, 'min_samples_leaf': 2, 'min_...",10,0.999679
8,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",20,0.999691
9,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",20,0.999704
10,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",20,0.999658
11,"{'max_depth': 20, 'min_samples_leaf': 1, 'min_...",20,0.999667
12,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",20,0.999690
13,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",20,0.999699
14,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",20,0.999674
15,"{'max_depth': 20, 'min_samples_leaf': 2, 'min_...",20,0.999679
16,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",None,0.999691
17,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",None,0.999704
18,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",None,0.999658
19,"{'max_depth': None, 'min_samples_leaf': 1, 'mi...",None,0.999667
20,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",None,0.999690
21,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",None,0.999699
22,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",None,0.999674
23,"{'max_depth': None, 'min_samples_leaf': 2, 'mi...",None,0.999679

## KNN Regressor

In [195]:
new_param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [20, 30, 40],
    'p': [1, 2]
}

new_grid = GridSearchCV(
    estimator=knn,
    param_grid=new_param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1
)

new_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='r2')

In [196]:
new_grid.cv_results_

{'mean_fit_time': array([0.01535997, 0.01533656, 0.01784554, 0.01667223, 0.01192856,
        0.01271439, 0.01122184, 0.0128521 , 0.01279674, 0.01177583,
        0.01467128, 0.01331468, 0.01297665, 0.012637  , 0.0155129 ,
        0.01650677, 0.01514878, 0.01484709, 0.01360235, 0.01136198,
        0.01125822, 0.01190095, 0.01355309, 0.01157484, 0.01256552,
        0.01363101, 0.01411581, 0.01549067, 0.01282921, 0.01505899,
        0.01425786, 0.0130619 , 0.01486678, 0.01501436, 0.01470103,
        0.01489897, 0.01263328, 0.01155319, 0.01234903, 0.01498828,
        0.01441832, 0.01621528, 0.01520534, 0.01553693, 0.015172  ,
        0.01631608, 0.01508627, 0.01696749, 0.01384048, 0.01530838,
        0.01497149, 0.01405144, 0.01284723, 0.0119945 , 0.01346965,
        0.015207  , 0.0144454 , 0.01255989, 0.01521602, 0.0154139 ,
        0.01518264, 0.01540089, 0.01551576, 0.01377945, 0.01342525,
        0.01248941, 0.01359291, 0.01153455, 0.01159387, 0.01007853,
        0.01005745, 0.00952415, 0.01182632, 0.01031837, 0.01140471,
        0.01283646, 0.01208711, 0.01231751, 0.01396232, 0.01420951,
        0.0101603 , 0.01364799, 0.0123138 , 0.01034179, 0.01085162,
        0.01321511, 0.01284614, 0.01132545, 0.01080689, 0.01048388,
        0.01014543, 0.01030812, 0.01035256, 0.00905986, 0.0114913 ,
        0.01067433, 0.01049862, 0.01074524, 0.01030159, 0.01160555,
        0.01127863, 0.01191044, 0.01261916, 0.01168017, 0.01282783,
        0.01149635, 0.01295786, 0.01451821, 0.01453052, 0.01411338,
        0.01437988, 0.01428642, 0.01355052, 0.01307473, 0.01422162,
        0.01302443, 0.01278362, 0.01153779, 0.0134697 , 0.01154447,
        0.01485896, 0.01320958, 0.0143755 , 0.01445103, 0.01367359,
        0.0146605 , 0.01336985, 0.01492543, 0.01410441, 0.01538343,
        0.01643138, 0.01768804, 0.01542902, 0.0147151 , 0.01562214,
        0.01488037, 0.01608639, 0.01648221, 0.01602101, 0.01747804,
        0.01463985, 0.01440234, 0.01555533, 0.01506886, 0.01454344,
        0.01548629, 0.01623211, 0.0139925 , 0.01363115, 0.01274514,
        0.01393185, 0.01668372, 0.01407108, 0.01411743, 0.01319385,
        0.01542401, 0.01398807, 0.01297417, 0.01361122, 0.01547074,
        0.01377039, 0.01483369, 0.0160388 , 0.01558766, 0.01370692,
        0.01527433, 0.01731567, 0.01528654, 0.01441865, 0.01683674,
        0.01636381, 0.01398578, 0.01582069, 0.01609802, 0.01511049,
        0.01457024, 0.01484232, 0.0142581 , 0.01343751, 0.01372318,
        0.01020284, 0.00741582, 0.01062474, 0.0112102 , 0.01081991,
        0.01029773, 0.01226473, 0.01078215, 0.01060004, 0.01205511,
        0.01035123, 0.01183271, 0.01101193, 0.01221619, 0.01193895,
        0.01040816, 0.01000171, 0.01036496, 0.0112443 , 0.01190848,
        0.01211171, 0.00966034, 0.01119127, 0.01171579, 0.01039348,
        0.01079187, 0.01201873, 0.0106235 , 0.0103548 , 0.01128044,
        0.01021299, 0.01261282, 0.01126552, 0.01058531, 0.01133595,
        0.01364098, 0.01364512, 0.01111655, 0.01150036, 0.0121336 ,
        0.01277504, 0.01121306, 0.01351581, 0.0118825 , 0.01097403,
        0.01100645, 0.01163101, 0.01268229, 0.01236453, 0.01374521,
        0.01111031, 0.00953598, 0.01100039, 0.01314759, 0.01005716,
        0.00816307, 0.00691152, 0.00668187, 0.0046031 , 0.00413251]),
 'std_fit_time': array([0.00225572, 0.00226812, 0.00245455, 0.00322114, 0.00122557,
        0.00162261, 0.0016712 , 0.0012006 , 0.00226373, 0.00180273,
        0.00220307, 0.00143461, 0.00138026, 0.00166184, 0.00377502,
        0.0023431 , 0.00087813, 0.0014366 , 0.00177796, 0.00145488,
        0.00169844, 0.00083677, 0.00120867, 0.00271136, 0.00314959,
        0.00206761, 0.00302343, 0.00297096, 0.00111106, 0.0011028 ,
        0.00304775, 0.00310297, 0.00136098, 0.00183241, 0.00172331,
        0.00196203, 0.00061198, 0.00127875, 0.00103578, 0.00343082,
        0.00147598, 0.00282974, 0.00234847, 0.00069099, 0.00227498,
        0.00191587, 0.00344153, 0.00149561, 0.00133043, 0.00099692,
        0.002627  , 0.00243508, 0.00178748, 0.00262434, 0.00212001,
        0.0034764 , 0.00334184, 0.00160446, 0.00220677, 0.00203938,
        0.00081202, 0.00217332, 0.00193711, 0.00261654, 0.0019849 ,
        0.00425693, 0.00396787, 0.00451312, 0.003607  , 0.00238234,
        0.00228911, 0.0031951 , 0.0032409 , 0.00317282, 0.00273747,
        0.00221852, 0.00415266, 0.00399568, 0.00195538, 0.00150611,
        0.00140457, 0.00189837, 0.00214893, 0.00114592, 0.00224611,
        0.00228692, 0.00149863, 0.00220932, 0.00270373, 0.00182183,
        0.00156648, 0.00221934, 0.00236336, 0.00142315, 0.00210493,
        0.00291562, 0.00136319, 0.00167881, 0.00210939, 0.00229575,
        0.00177347, 0.00285934, 0.0019382 , 0.00074243, 0.00268566,
        0.00236778, 0.00252276, 0.00257143, 0.0023643 , 0.0027802 ,
        0.00184921, 0.00143941, 0.00174561, 0.00069069, 0.00193341,
        0.00182205, 0.00279053, 0.00155065, 0.00276426, 0.00310921,
        0.00221549, 0.00274952, 0.00207373, 0.00259713, 0.00242818,
        0.00271661, 0.00242624, 0.00123771, 0.0013018 , 0.00243099,
        0.00322335, 0.00167755, 0.00203829, 0.0017027 , 0.0020526 ,
        0.00163705, 0.00404804, 0.00216506, 0.00346476, 0.00059013,
        0.00150328, 0.00061617, 0.00223428, 0.00088098, 0.00196537,
        0.0014771 , 0.00080541, 0.00161095, 0.00165701, 0.00166378,
        0.00364927, 0.00222157, 0.00237101, 0.00154195, 0.00064673,
        0.00290775, 0.00279434, 0.00129771, 0.00236715, 0.00234795,
        0.00296538, 0.00272105, 0.00459588, 0.00250519, 0.00119565,
        0.00292542, 0.00195363, 0.0010354 , 0.00259313, 0.0010242 ,
        0.00173559, 0.00166286, 0.00196786, 0.00215025, 0.00125243,
        0.00165667, 0.00215117, 0.00179111, 0.00243936, 0.00186413,
        0.00192764, 0.00172422, 0.00214329, 0.00200763, 0.00297235,
        0.00155259, 0.00198795, 0.00245049, 0.00197122, 0.00260306,
        0.00355825, 0.00166114, 0.00206691, 0.00234233, 0.00270603,
        0.0013527 , 0.00231497, 0.00201397, 0.00088095, 0.00038967,
        0.00117185, 0.0009116 , 0.00050121, 0.00063833, 0.00183204,
        0.00213891, 0.00314968, 0.00151824, 0.00221458, 0.00208103,
        0.00193788, 0.00283049, 0.00178987, 0.00157374, 0.00022645,
        0.00372671, 0.00253328, 0.00228699, 0.00309066, 0.00062533,
        0.00267884, 0.00277994, 0.00195049, 0.0008714 , 0.00149539,
        0.00183149, 0.00065026, 0.00124446, 0.00098248, 0.00261337,
        0.0020227 , 0.00270544, 0.00214663, 0.0014947 , 0.00373812,
        0.00087487, 0.00084685, 0.00064099, 0.00053297, 0.00030692]),
 'mean_score_time': array([0.01149597, 0.01052046, 0.01218691, 0.01085038, 0.00913877,
        0.00853333, 0.00955949, 0.00905561, 0.01049047, 0.01298947,
        0.00997705, 0.01174817, 0.01135821, 0.01108804, 0.01161809,
        0.0116302 , 0.01071653, 0.01287718, 0.01108065, 0.01036296,
        0.01128793, 0.01125417, 0.00978618, 0.01020327, 0.01275744,
        0.01329103, 0.0130362 , 0.01110387, 0.01126032, 0.01189938,
        0.01326299, 0.01238871, 0.01363931, 0.0135776 , 0.01452732,
        0.01171708, 0.01381178, 0.01134477, 0.01012859, 0.01430588,
        0.01526175, 0.01431613, 0.01357074, 0.01317601, 0.01306839,
        0.0131813 , 0.01187897, 0.01273947, 0.01464939, 0.01329632,
        0.01130719, 0.01005116, 0.01121774, 0.01069145, 0.01308637,
        0.01153245, 0.01207981, 0.01396465, 0.0129427 , 0.01363773,
        0.01191907, 0.01198435, 0.01044788, 0.0115593 , 0.01228795,
        0.01220531, 0.00893197, 0.00891633, 0.01036487, 0.00728889,
        0.00893779, 0.00953488, 0.00799665, 0.01275539, 0.01095357,
        0.01036253, 0.0113327 , 0.01159263, 0.010393  , 0.01096578,
        0.0098752 , 0.01148076, 0.01077766, 0.00971465, 0.01154566,
        0.01129045, 0.00898304, 0.01015468, 0.00912981, 0.00935621,
        0.00930414, 0.00984478, 0.00955868, 0.0105135 , 0.00944376,
        0.01039257, 0.01002431, 0.01045971, 0.01048322, 0.01129065,
        0.01069984, 0.01162024, 0.01274023, 0.01310549, 0.01123676,
        0.01316829, 0.0126821 , 0.011657  , 0.01233277, 0.01277533,
        0.01063032, 0.01174273, 0.01100707, 0.01448107, 0.01104217,
        0.01153493, 0.01202712, 0.01272125, 0.00939288, 0.0114996 ,
        0.01064825, 0.01138291, 0.01112738, 0.01099105, 0.01283407,
        0.01441493, 0.01268225, 0.01354833, 0.01162066, 0.01483483,
        0.01161246, 0.01231756, 0.01241755, 0.01378293, 0.01433997,
        0.01473341, 0.01307549, 0.01438584, 0.0129467 , 0.01130052,
        0.0136034 , 0.0139535 , 0.01186404, 0.01266799, 0.01320539,
        0.0141818 , 0.01198196, 0.01122985, 0.01216135, 0.01382661,
        0.01297016, 0.01106691, 0.0122993 , 0.01275635, 0.01173997,
        0.0121285 , 0.01231365, 0.01321774, 0.01536479, 0.01460347,
        0.01260824, 0.01313252, 0.01348186, 0.01345525, 0.01486244,
        0.01474924, 0.01269007, 0.01290865, 0.01442981, 0.01423607,
        0.01061544, 0.01373577, 0.01251245, 0.01224422, 0.01314683,
        0.01222415, 0.01290374, 0.0109529 , 0.01294971, 0.01196618,
        0.03104839, 0.02749   , 0.02444949, 0.0276926 , 0.02421875,
        0.02667694, 0.0291388 , 0.02805276, 0.02972522, 0.02887692,
        0.02939882, 0.02916756, 0.0282732 , 0.02699223, 0.02882285,
        0.03043303, 0.02947001, 0.02755222, 0.02534356, 0.0290132 ,
        0.02720494, 0.02754064, 0.03019295, 0.02893724, 0.02629418,
        0.02903619, 0.0308835 , 0.02987804, 0.02800565, 0.02762332,
        0.02936544, 0.03032951, 0.02812119, 0.02917795, 0.03231764,
        0.02964849, 0.02760549, 0.0281755 , 0.03029766, 0.03004827,
        0.02930484, 0.02911015, 0.0298439 , 0.03226886, 0.02849731,
        0.029914  , 0.0318449 , 0.02899976, 0.02846689, 0.02701874,
        0.02978964, 0.02617283, 0.02842546, 0.02767935, 0.02459474,
        0.02171059, 0.01865816, 0.01279616, 0.01040506, 0.01142144]),
 'std_score_time': array([0.00108102, 0.00112879, 0.00240465, 0.00183176, 0.0017486 ,
        0.00067209, 0.00121859, 0.00160525, 0.00178188, 0.00144023,
        0.00188663, 0.00155845, 0.00150208, 0.00214668, 0.00140124,
        0.00099862, 0.0009091 , 0.00153246, 0.00201014, 0.00140671,
        0.0005576 , 0.00117453, 0.00230527, 0.00194788, 0.00137315,
        0.00137867, 0.00203941, 0.00222847, 0.0023278 , 0.00271363,
        0.00208738, 0.00124124, 0.00090326, 0.00188059, 0.0021105 ,
        0.00163188, 0.00094125, 0.00287629, 0.00183917, 0.00272258,
        0.00060095, 0.00153932, 0.00235298, 0.00098995, 0.0015134 ,
        0.0013983 , 0.00202671, 0.00245276, 0.00202653, 0.00201337,
        0.00239602, 0.00125898, 0.00355182, 0.00120379, 0.00316837,
        0.00145976, 0.00177917, 0.00185186, 0.00146979, 0.00131837,
        0.00108868, 0.00254399, 0.00064974, 0.00088727, 0.00411304,
        0.00304518, 0.00260713, 0.00136206, 0.00332472, 0.00173384,
        0.00195812, 0.002215  , 0.00171636, 0.00153157, 0.00227007,
        0.00155419, 0.00167845, 0.00039642, 0.00160078, 0.00166646,
        0.00173735, 0.0016646 , 0.00141542, 0.00175671, 0.00220269,
        0.00150941, 0.00211441, 0.00123086, 0.00210325, 0.00092638,
        0.00055971, 0.00066094, 0.00279338, 0.00276004, 0.00115873,
        0.00047231, 0.00157418, 0.00227396, 0.0021372 , 0.00099792,
        0.0013555 , 0.00300155, 0.00071617, 0.00243721, 0.00095363,
        0.00221426, 0.00132769, 0.00115199, 0.00146726, 0.0022821 ,
        0.0028846 , 0.00214937, 0.00168074, 0.00192583, 0.00134427,
        0.00301387, 0.00340356, 0.00275092, 0.00166959, 0.00134839,
        0.00113889, 0.00095765, 0.00199749, 0.00079498, 0.00207175,
        0.00239065, 0.00085623, 0.00271388, 0.00101829, 0.00215062,
        0.00244061, 0.00108003, 0.00121944, 0.00169562, 0.00280551,
        0.00221332, 0.00199412, 0.00191596, 0.00286382, 0.00116522,
        0.00229703, 0.0019101 , 0.00072122, 0.00133722, 0.00192363,
        0.00240099, 0.0008942 , 0.0004802 , 0.00130146, 0.00087396,
        0.00149727, 0.00251446, 0.00143098, 0.00145464, 0.00111016,
        0.00332454, 0.00236722, 0.00108714, 0.00325977, 0.00242327,
        0.00324389, 0.00169965, 0.00335411, 0.00243016, 0.00267739,
        0.00237436, 0.00280753, 0.00222569, 0.00282943, 0.00198091,
        0.00099096, 0.00206417, 0.00264572, 0.00210233, 0.00185659,
        0.00244456, 0.0029808 , 0.00254644, 0.00273322, 0.00179391,
        0.00851389, 0.00632596, 0.0043285 , 0.0017841 , 0.00333911,
        0.00597219, 0.00415616, 0.00301403, 0.00253189, 0.00093597,
        0.00154873, 0.00379804, 0.00192224, 0.00161964, 0.00241188,
        0.00258486, 0.00446746, 0.00158881, 0.0026392 , 0.00230562,
        0.00089446, 0.00186389, 0.00171677, 0.00285807, 0.00186013,
        0.0029577 , 0.00212286, 0.0016489 , 0.00142875, 0.00157107,
        0.00160278, 0.0029705 , 0.00329083, 0.00243456, 0.00309924,
        0.00211123, 0.00036065, 0.00208779, 0.00227174, 0.0034392 ,
        0.00113515, 0.00282908, 0.00245936, 0.00140723, 0.0029972 ,
        0.00118633, 0.0038666 , 0.00277625, 0.00120641, 0.00087497,
        0.00340195, 0.00536848, 0.00322058, 0.00180992, 0.0029107 ,
        0.00246128, 0.00158834, 0.00199458, 0.00031131, 0.00026702]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'auto', 'auto', 'auto', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_leaf_size': masked_array(data=[20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                    20, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 30, 30, 30,
                    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 40, 40,
                    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
                    40, 40, 40, 40, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 30, 30, 30, 30,
                    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
                    30, 30, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
                    40, 40, 40, 40, 40, 40, 40, 40, 20, 20, 20, 20, 20, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
                    30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
                    30, 30, 30, 30, 30, 30, 40, 40, 40, 40, 40, 40, 40, 40,
                    40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 20, 20,
                    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,

In [197]:
result2 = pd.DataFrame(new_grid.cv_results_)

In [198]:
result2

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015360,0.002256,0.011496,0.001081,auto,20,3,1,uniform,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.556733,0.625694,0.530452,0.617979,0.630439,0.592259,0.040790,118
1,0.015337,0.002268,0.010520,0.001129,auto,20,3,1,distance,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.561898,0.632841,0.535439,0.627716,0.635266,0.598632,0.041715,113
2,0.017846,0.002455,0.012187,0.002405,auto,20,3,2,uniform,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.410184,0.502132,0.298215,0.464415,0.560820,0.447153,0.089208,239
3,0.016672,0.003221,0.010850,0.001832,auto,20,3,2,distance,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.421098,0.516663,0.321409,0.475796,0.568620,0.460717,0.084825,227
4,0.011929,0.001226,0.009139,0.001749,auto,20,5,1,uniform,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.538109,0.645971,0.584879,0.630067,0.675985,0.615002,0.048425,69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,0.008163,0.000875,0.021711,0.002461,brute,40,9,2,distance,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.485673,0.541882,0.429549,0.550343,0.596355,0.520761,0.057596,132
236,0.006912,0.000847,0.018658,0.001588,brute,40,11,1,uniform,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.546598,0.636757,0.560967,0.640475,0.674494,0.611858,0.049419,83
237,0.006682,0.000641,0.012796,0.001995,brute,40,11,1,distance,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.564755,0.647310,0.579573,0.654925,0.688346,0.626982,0.047073,32
238,0.004603,0.000533,0.010405,0.000311,brute,40,11,2,uniform,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.461765,0.525899,0.444179,0.518087,0.575584,0.505103,0.047241,195
239,0.004133,0.000307,0.011421,0.000267,brute,40,11,2,distance,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.475953,0.539762,0.456661,0.537853,0.593442,0.520734,0.049097,135

In [199]:
result2[['param_algorithm','params','mean_test_score']]

,param_algorithm,params,mean_test_score
0,auto,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.592259
1,auto,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.598632
2,auto,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.447153
3,auto,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.460717
4,auto,"{'algorithm': 'auto', 'leaf_size': 20, 'n_neig...",0.615002
...,...,...,...
235,brute,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.520761
236,brute,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.611858
237,brute,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.626982
238,brute,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.505103
239,brute,"{'algorithm': 'brute', 'leaf_size': 40, 'n_nei...",0.520734

# Randomized Search CV

In [200]:
from sklearn.model_selection import RandomizedSearchCV

## Random Forest Regressor

In [201]:
classifier_r = RandomizedSearchCV((rf_model),{
    'n_estimators': [100, 200, 300, 500],
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', None],
    'bootstrap': [True, False]
},n_iter = 20,cv = 5,return_train_score = False)

In [202]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
                   n_iter=20,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [None, 10, 20, 30, 40],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]})

In [203]:
result3 = pd.DataFrame(classifier_r.cv_results_)

In [204]:
result3

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_estimators,param_min_samples_split,param_min_samples_leaf,param_max_features,param_max_depth,param_bootstrap,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,3.315227,0.093717,0.052711,0.008147,500,5,1,None,20,False,"{'n_estimators': 500, 'min_samples_split': 5, ...",0.999392,0.999309,0.999277,0.998955,0.999500,0.999287,0.000183,6
1,1.632442,0.014070,0.073170,0.001830,500,2,1,sqrt,40,True,"{'n_estimators': 500, 'min_samples_split': 2, ...",0.956198,0.955465,0.955750,0.951603,0.961864,0.956176,0.003285,9
2,0.684726,0.006388,0.036184,0.000734,300,10,1,log2,40,True,"{'n_estimators': 300, 'min_samples_split': 10,...",0.942228,0.934488,0.931852,0.930310,0.944305,0.936637,0.005615,16
3,0.705122,0.007463,0.039660,0.002034,300,2,4,sqrt,None,False,"{'n_estimators': 300, 'min_samples_split': 2, ...",0.950827,0.939857,0.944013,0.945320,0.954074,0.946818,0.005046,13
4,1.900562,0.027493,0.043877,0.001135,300,2,1,None,None,True,"{'n_estimators': 300, 'min_samples_split': 2, ...",0.999753,0.999652,0.999715,0.999545,0.999841,0.999701,0.000099,1
5,0.231830,0.005769,0.014007,0.000802,100,10,2,log2,None,True,"{'n_estimators': 100, 'min_samples_split': 10,...",0.936341,0.924861,0.922086,0.931843,0.942082,0.931443,0.007324,20
6,0.802499,0.022063,0.039384,0.000877,300,2,2,sqrt,40,True,"{'n_estimators': 300, 'min_samples_split': 2, ...",0.950452,0.944847,0.946261,0.943469,0.957211,0.948448,0.004967,12
7,0.484997,0.003327,0.014497,0.000364,100,5,1,None,None,True,"{'n_estimators': 100, 'min_samples_split': 5, ...",0.999703,0.999617,0.999657,0.999505,0.999808,0.999658,0.000100,4
8,0.765487,0.005396,0.039140,0.001984,300,5,2,log2,None,True,"{'n_estimators': 300, 'min_samples_split': 5, ...",0.949782,0.938946,0.945082,0.940227,0.950266,0.944861,0.004689,14
9,0.567212,0.004260,0.028079,0.000347,200,5,1,sqrt,40,False,"{'n_estimators': 200, 'min_samples_split': 5, ...",0.960820,0.957365,0.958174,0.957032,0.961971,0.959072,0.001967,8
10,1.901786,0.009669,0.036764,0.001251,300,2,2,None,10,False,"{'n_estimators': 300, 'min_samples_split': 2, ...",0.999409,0.999383,0.999377,0.999048,0.999548,0.999353,0.000165,5
11,1.928202,0.046166,0.035406,0.000908,300,5,1,None,None,False,"{'n_estimators': 300, 'min_samples_split': 5, ...",0.999399,0.999305,0.999278,0.998954,0.999495,0.999286,0.000183,7
12,0.650180,0.001418,0.030832,0.001040,200,2,1,sqrt,40,True,"{'n_estimators': 200, 'min_samples_split': 2, ...",0.954674,0.951117,0.954139,0.947314,0.961135,0.953676,0.004558,10
13,0.454675,0.005669,0.025342,0.000734,200,10,2,sqrt,30,True,"{'n_estimators': 200, 'min_samples_split': 10,...",0.937949,0.928257,0.933175,0.932960,0.945690,0.935606,0.005901,19
14,0.675440,0.004617,0.036441,0.001229,300,5,4,sqrt,30,True,"{'n_estimators': 300, 'min_samples_split': 5, ...",0.937188,0.928332,0.935699,0.934951,0.942067,0.935647,0.004418,18
15,0.488396,0.004112,0.014504,0.000233,100,2,2,None,10,True,"{'n_estimators': 100, 'min_samples_split': 2, ...",0.999755,0.999632,0.999689,0.999543,0.999827,0.999689,0.000098,2
16,0.233897,0.003959,0.014812,0.000687,100,5,4,log2,10,False,"{'n_estimators': 100, 'min_samples_split': 5, ...",0.940627,0.925297,0.933745,0.940134,0.946799,0.937320,0.007294,15
17,2.414314,0.016338,0.062690,0.001031,500,5,1,None,None,True,"{'n_estimators': 500, 'min_samples_split': 5, ...",0.999744,0.999601,0.999688,0.999486,0.999814,0.999667,0.000114,3
18,1.353722,0.040710,0.065752,0.002997,500,5,1,sqrt,20,True,"{'n_estimators': 500, 'min_samples_split': 5, ...",0.953430,0.943741,0.950674,0.945774,0.958277,0.950379,0.005235,11
19,0.695699,0.016145,0.036129,0.000997,300,10,1,sqrt,40,True,"{'n_estimators': 300, 'min_samples_split': 10,...",0.942228,0.934488,0.931852,0.930310,0.944305,0.936637,0.005615,16

In [205]:
result3[['params','param_max_features','mean_test_score']]

,params,param_max_features,mean_test_score
0,"{'n_estimators': 500, 'min_samples_split': 5, ...",None,0.999287
1,"{'n_estimators': 500, 'min_samples_split': 2, ...",sqrt,0.956176
2,"{'n_estimators': 300, 'min_samples_split': 10,...",log2,0.936637
3,"{'n_estimators': 300, 'min_samples_split': 2, ...",sqrt,0.946818
4,"{'n_estimators': 300, 'min_samples_split': 2, ...",None,0.999701
5,"{'n_estimators': 100, 'min_samples_split': 10,...",log2,0.931443
6,"{'n_estimators': 300, 'min_samples_split': 2, ...",sqrt,0.948448
7,"{'n_estimators': 100, 'min_samples_split': 5, ...",None,0.999658
8,"{'n_estimators': 300, 'min_samples_split': 5, ...",log2,0.944861
9,"{'n_estimators': 200, 'min_samples_split': 5, ...",sqrt,0.959072
10,"{'n_estimators': 300, 'min_samples_split': 2, ...",None,0.999353
11,"{'n_estimators': 300, 'min_samples_split': 5, ...",None,0.999286
12,"{'n_estimators': 200, 'min_samples_split': 2, ...",sqrt,0.953676
13,"{'n_estimators': 200, 'min_samples_split': 10,...",sqrt,0.935606
14,"{'n_estimators': 300, 'min_samples_split': 5, ...",sqrt,0.935647
15,"{'n_estimators': 100, 'min_samples_split': 2, ...",None,0.999689
16,"{'n_estimators': 100, 'min_samples_split': 5, ...",log2,0.937320
17,"{'n_estimators': 500, 'min_samples_split': 5, ...",None,0.999667
18,"{'n_estimators': 500, 'min_samples_split': 5, ...",sqrt,0.950379
19,"{'n_estimators': 300, 'min_samples_split': 10,...",sqrt,0.936637

## KNN Regressor

In [206]:
classifier_knn = RandomizedSearchCV((knn),{
    'n_neighbors': [3, 5, 7, 9, 11, 15, 21],
    'weights': ['uniform', 'distance'],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [20, 30, 40, 50],
    'p': [1, 2]
},n_iter = 20,cv = 5,return_train_score = False)

In [207]:
classifier_knn.fit(X,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsRegressor(), n_iter=20,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'leaf_size': [20, 30, 40, 50],
                                        'n_neighbors': [3, 5, 7, 9, 11, 15, 21],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']})

In [208]:
result4 = pd.DataFrame(classifier_knn.cv_results_)

In [209]:
result4

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_weights,param_p,param_n_neighbors,param_leaf_size,param_algorithm,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006347,0.000890,0.005944,0.001133,distance,1,9,50,ball_tree,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",0.613669,0.680852,0.683982,0.678456,0.708180,0.673028,0.031527,2
1,0.004086,0.000767,0.003262,0.000415,uniform,2,5,20,ball_tree,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.506458,0.586060,0.585719,0.558245,0.574639,0.562224,0.029665,9
2,0.004575,0.000349,0.003390,0.000059,uniform,2,15,20,kd_tree,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.465690,0.544718,0.555934,0.538103,0.566359,0.534161,0.035570,19
3,0.002234,0.000047,0.018668,0.002570,uniform,2,3,20,brute,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.483049,0.607969,0.583701,0.550483,0.566976,0.558436,0.042217,13
4,0.003809,0.000825,0.003674,0.000325,uniform,1,7,30,ball_tree,"{'weights': 'uniform', 'p': 1, 'n_neighbors': ...",0.597392,0.668953,0.667500,0.677241,0.696610,0.661539,0.033710,5
5,0.003782,0.000022,0.003767,0.000113,distance,1,11,40,kd_tree,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",0.609971,0.682855,0.688425,0.666439,0.696768,0.668892,0.031084,3
6,0.004122,0.000030,0.003456,0.000061,uniform,2,15,20,auto,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.465690,0.544718,0.555934,0.538103,0.566359,0.534161,0.035570,19
7,0.003803,0.000089,0.003491,0.000171,uniform,1,7,50,kd_tree,"{'weights': 'uniform', 'p': 1, 'n_neighbors': ...",0.594825,0.666636,0.672134,0.674340,0.689369,0.659461,0.033184,6
8,0.003375,0.000050,0.002918,0.000054,distance,2,7,20,ball_tree,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",0.496126,0.589364,0.589618,0.579244,0.602412,0.571353,0.038325,7
9,0.003750,0.000008,0.003559,0.000042,distance,2,15,50,kd_tree,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",0.484629,0.565136,0.573143,0.560389,0.586340,0.553927,0.035748,14
10,0.003232,0.000083,0.003587,0.000053,distance,1,11,40,ball_tree,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",0.611710,0.683220,0.685439,0.666084,0.695707,0.668432,0.029916,4
11,0.003770,0.000009,0.003321,0.000089,uniform,2,11,30,auto,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.466255,0.547753,0.566092,0.561759,0.568462,0.542064,0.038579,16
12,0.003885,0.000135,0.003171,0.000040,uniform,2,7,40,auto,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.474347,0.570362,0.574438,0.561999,0.583122,0.552854,0.039838,15
13,0.004115,0.000013,0.002948,0.000091,uniform,2,3,20,kd_tree,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.483941,0.607093,0.583371,0.550494,0.570456,0.559071,0.041819,12
14,0.003166,0.000039,0.003271,0.000185,distance,2,11,50,ball_tree,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",0.487013,0.567611,0.580766,0.578653,0.587812,0.560371,0.037248,11
15,0.003763,0.000040,0.003252,0.000050,uniform,2,9,30,kd_tree,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.456484,0.551307,0.555452,0.563977,0.579267,0.541297,0.043474,17
16,0.003317,0.000039,0.002950,0.000022,distance,2,9,20,ball_tree,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",0.480586,0.574902,0.572820,0.582386,0.596417,0.561422,0.041256,10
17,0.002188,0.000022,0.007652,0.000228,uniform,2,15,30,brute,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",0.464271,0.544796,0.555472,0.538271,0.568368,0.534236,0.036438,18
18,0.003906,0.000168,0.003252,0.000040,distance,2,7,40,kd_tree,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",0.495567,0.589226,0.589632,0.579379,0.600077,0.570776,0.038170,8
19,0.002163,0.000023,0.007643,0.000140,distance,1,5,30,brute,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",0.616470,0.708606,0.678737,0.675033,0.697731,0.675315,0.031891,1

In [210]:
result4[['params','param_weights','mean_test_score']]

,params,param_weights,mean_test_score
0,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",distance,0.673028
1,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.562224
2,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.534161
3,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.558436
4,"{'weights': 'uniform', 'p': 1, 'n_neighbors': ...",uniform,0.661539
5,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",distance,0.668892
6,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.534161
7,"{'weights': 'uniform', 'p': 1, 'n_neighbors': ...",uniform,0.659461
8,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",distance,0.571353
9,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",distance,0.553927
10,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",distance,0.668432
11,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.542064
12,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.552854
13,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.559071
14,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",distance,0.560371
15,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.541297
16,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",distance,0.561422
17,"{'weights': 'uniform', 'p': 2, 'n_neighbors': ...",uniform,0.534236
18,"{'weights': 'distance', 'p': 2, 'n_neighbors':...",distance,0.570776
19,"{'weights': 'distance', 'p': 1, 'n_neighbors':...",distance,0.675315